# Change the following values! DO NOT KEEP AS DEFAULT
# --- CREDENTIALS BEGIN ---
MONGODB_USER="admin"
MONGODB_PASSWORD="password"
# --- CREDENTIALS_END   ---

# --- CONFIG BEGIN ---\
CORNERSTONE_WEBSITE_URL="local.cornerstone.com"
CORNERSTONE_WEBSITE_NAME="Cornerstone App"
# --- CONFIG END


export MONGODB_USER
export MONGODB_PASSWORD
export CORNERSTONE_WEBSITE_URL
export CORNERSTONE_WEBSITE_NAME