# Removes these environment variables
# --- CREDENTIALS BEGIN ---
MONGODB_USER=""
MONGODB_PASSWORD=""
# --- CREDENTIALS_END   ---

# --- CONFIG BEGIN ---\
CORNERSTONE_WEBSITE_URL=""
CORNERSTONE_WEBSITE_NAME=""
CORNERSTONE_EMAIL=""
CORNERSTONE_EMAIL_PASSWORD=""
CORNERSTONE_ADMIN_USER=""
CORNERSTONE_ADMIN_PASSWORD=""
CORNERSTONE_TIMEZONE=""
# --- CONFIG END


export MONGODB_USER
export MONGODB_PASSWORD
export CORNERSTONE_WEBSITE_URL
export CORNERSTONE_WEBSITE_NAME
export CORNERSTONE_EMAIL
export CORNERSTONE_EMAIL_PASSWORD
export CORNERSTONE_ADMIN_USER
export CORNERSTONE_ADMIN_PASSWORD
export CORNERSTONE_TIMEZONE