# Removes these environment variables
# --- CREDENTIALS BEGIN ---
DB_USER=""
DB_PASSWORD=""
# --- CREDENTIALS_END   ---

# --- CONFIG BEGIN ---\
CORNERSTONE_WEBSITE_URL=""
CORNERSTONE_API_URL="api.cornerstone.test"
CORNERSTONE_WEBSITE_NAME=""
CORNERSTONE_EMAIL=""
CORNERSTONE_EMAIL_PASSWORD=""
CORNERSTONE_ADMIN_USER=""
CORNERSTONE_ADMIN_PASSWORD=""
CORNERSTONE_TIMEZONE=""
CORNERSTONE_SYSTEM_USER=""
# --- CONFIG END


export DB_USER
export DB_PASSWORD
export CORNERSTONE_WEBSITE_URL
export CORNERSTONE_API_URL
export CORNERSTONE_WEBSITE_NAME
export CORNERSTONE_EMAIL
export CORNERSTONE_EMAIL_PASSWORD
export CORNERSTONE_ADMIN_USER
export CORNERSTONE_ADMIN_PASSWORD
export CORNERSTONE_TIMEZONE
export CORNERSTONE_SYSTEM_USER