# Change the following values! DO NOT KEEP AS DEFAULT
# --- CREDENTIALS BEGIN ---
DB_USER="admin"
DB_PASSWORD="password"
# --- CREDENTIALS_END   ---

# --- CONFIG BEGIN ---\
CORNERSTONE_WEBSITE_URL="local.cornerstone.com"
CORNERSTONE_API_URL="api-local.cornerstone.com"
CORNERSTONE_WEBSITE_NAME="Cornerstone App"
CORNERSTONE_EMAIL="you\@example.com"
CORNERSTONE_EMAIL_PASSWORD="change_password_123"
CORNERSTONE_ADMIN_USER="changeme"
CORNERSTONE_ADMIN_PASSWORD="change_me_123"
CORNERSTONE_TIMEZONE="PST"
CORNERSTONE_SYSTEM_USER="ubuntu"
# --- CONFIG END


export MONGODB_USER
export MONGODB_PASSWORD
export CORNERSTONE_WEBSITE_URL
export CORNERSTONE_API_URL
export CORNERSTONE_WEBSITE_NAME
export CORNERSTONE_EMAIL
export CORNERSTONE_EMAIL_PASSWORD
export CORNERSTONE_ADMIN_USER
export CORNERSTONE_ADMIN_PASSWORD
export CORNERSTONE_TIMEZONE
export CORNERSTONE_SYSTEM_USER